web:
    restart: always
    image: nginx
    ports:
        - "80:80"
    volumes:
        - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
        - /etc/localtime:/etc/localtime:ro # Share timezone data with host
    links:
        - graylog

fluentd:
    restart: always
    image: eeacms/fluentd
    links:
        - graylog
    ports:
        - "5140:5140/udp"
    volumes_from:
        - data
    volumes:
        - ./fluentd/fluent.conf:/etc/fluent/fluent.conf:ro # Configuration
        - /etc/localtime:/etc/localtime:ro # Share timezone data with host

graylog:
    restart: always
    image: eeacms/graylog2
    env_file:
        - .secret.env
        - master.env
    # Comment this out in order to send GELF messages for a GELF input
    #ports: 
    #    - "12201:12201/udp"
    volumes_from:
        - data
    links:
        - rabbitmq
    volumes:
        - /etc/localtime:/etc/localtime:ro # Share timezone data with host


rabbitmq:
    restart: always
    image: rabbitmq:3-management
    ports:
        - "5672:5672"
    environment:
        - RABBITMQ_NODENAME=rabbit-logs
    hostname: rabbit-logs

# Run this one-time only in order to setup rabbitmq
# Do the configuration from container in order not to expose
# the configuration REST API globally
rabbitmqconfig:
    image: radial/busyboxplus:curl
    volumes:
        - ./rabbitconfig/config.sh:/config.sh:ro
    links:
        - rabbitmq
    environment:
        - BROKER=rabbitmq
    command: /config.sh

data:
    image: busybox
    volumes:
        - /data
        - /log
    command: true
